app2/urls.py
from django.urls import path
from app2.views import *
app_name='hari'

urlpatterns=[
    path('third/',third,name='third'),
]

projectr/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import *
urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',first,name='first'),
    path('second/',second,name='second'),
    path('third/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def first(request):
    return render(request,'first.html')

def second(request):
    return render(request,'second.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def third(request):
    return render(request,'third.html')

templates/first.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i am using first</h1>

        <h2><a href="{% url 'second' %}"> go to second</a></h2>
        <h2><a href="{% url 'hari:third' %}">go to third</a></h2>
    </center>
</body>
</html>

templates/second.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i am using second html</h1>

        <h2><a href="{% url 'first' %}">go to first</a></h2>
        <h2><a href="{% url 'hari:third' %}">go to third</a></h2>
    </center>
</body>
</html>

templates/third.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>i am using third html</h1>

        <h2><a href="{% url 'first' %}">fo to first</a></h2>

        <h2><a href="{% url 'second' %}"></a></h2>
    </center>
</body>
</html>